apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flet-montrg

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- secret.yaml
- hpa.yaml
- network-policy.yaml

commonLabels:
  app: realtime-service
  version: v1.0.0