apiVersion: apps/v1
kind: Deployment
metadata:
  name: thresholds-service
  namespace: flet-montrg
  labels:
    app: thresholds-service
    version: v1.0.0
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: thresholds-service
  template:
    metadata:
      labels:
        app: thresholds-service
        version: v1.0.0
    spec:
      containers:
      - name: thresholds-service
        image: flet-montrg/thresholds-service:latest  
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: thresholds-service-config
              key: APP_NAME
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: thresholds-service-config
              key: APP_VERSION
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: thresholds-service-config
              key: ENVIRONMENT
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: thresholds-service-config
              key: HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: thresholds-service-config
              key: PORT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: thresholds-service-config
              key: LOG_LEVEL
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: thresholds-service-config
              key: CORS_ORIGINS
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: thresholds-service-config
              key: DEBUG
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: thresholds-service-secret
              key: DATABASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
