apiVersion: v1
kind: Secret
metadata:
  name: location-service-secret
  namespace: flet-montrg
  labels:
    app: location-service
type: Opaque
data:
  # postgresql+asyncpg://...@docker-postgres:5432/hq ??Service(Endpoints?�Docker postgres IP); IP??external-docker-postgres/endpoints.yaml
  DATABASE_URL: ""
